#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _ar_traub_reg();
extern void _Ca_reg();
extern void _Ca_HVA_reg();
extern void _Ca_LVAst_reg();
extern void _cadad_reg();
extern void _cadyn_reg();
extern void _CaDynamics_E2_reg();
extern void _cagk_reg();
extern void _cal_mh_reg();
extern void _cal_mig_reg();
extern void _can_mig_reg();
extern void _cancr_reg();
extern void _canin_reg();
extern void _cat_mig_reg();
extern void _cat_traub_reg();
extern void _catcb_reg();
extern void _ch_CavL_reg();
extern void _ch_CavN_reg();
extern void _ch_KCaS_reg();
extern void _ch_Kdrfastngf_reg();
extern void _ch_KvAngf_reg();
extern void _ch_KvCaB_reg();
extern void _ch_leak_reg();
extern void _ch_Navngf_reg();
extern void _DetAMPANMDA_reg();
extern void _DetGABAAB_reg();
extern void _gabab_reg();
extern void _h_BS_reg();
extern void _h_harnett_reg();
extern void _h_kole_reg();
extern void _h_migliore_reg();
extern void _HCN1_reg();
extern void _HH2_reg();
extern void _hin_reg();
extern void _htc_reg();
extern void _IC_reg();
extern void _ican_sidi_reg();
extern void _iccr_reg();
extern void _iconc_Ca_reg();
extern void _Ih_reg();
extern void _ikscr_reg();
extern void _IKsin_reg();
extern void _Im_reg();
extern void _IT_reg();
extern void _IT2_reg();
extern void _K_Pst_reg();
extern void _K_Tst_reg();
extern void _kap_BS_reg();
extern void _kapcb_reg();
extern void _kapin_reg();
extern void _kBK_reg();
extern void _kca_reg();
extern void _kctin_reg();
extern void _kdmc_BS_reg();
extern void _kdr_BS_reg();
extern void _kdrcr_reg();
extern void _kdrin_reg();
extern void _KdShu2007_reg();
extern void _kl_reg();
extern void _km_reg();
extern void _kv_reg();
extern void _my_exp2syn_reg();
extern void _MyExp2SynBB_reg();
extern void _MyExp2SynNMDABB_reg();
extern void _nafcr_reg();
extern void _nafx_reg();
extern void _Nap_Et2_reg();
extern void _nap_sidi_reg();
extern void _NaTa_t_reg();
extern void _NaTs2_t_reg();
extern void _nax_BS_reg();
extern void _naz_reg();
extern void _Nca_reg();
extern void _ProbAMPANMDA_EMS_reg();
extern void _ProbGABAAB_EMS_reg();
extern void _savedist_reg();
extern void _SK_E2_reg();
extern void _SKv3_1_reg();
extern void _StochKv_reg();
extern void _StochKv_deterministic_reg();
extern void _tia_reg();
extern void _vecstim_reg();
extern void _xtra_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," ar_traub.mod");
fprintf(stderr," Ca.mod");
fprintf(stderr," Ca_HVA.mod");
fprintf(stderr," Ca_LVAst.mod");
fprintf(stderr," cadad.mod");
fprintf(stderr," cadyn.mod");
fprintf(stderr," CaDynamics_E2.mod");
fprintf(stderr," cagk.mod");
fprintf(stderr," cal_mh.mod");
fprintf(stderr," cal_mig.mod");
fprintf(stderr," can_mig.mod");
fprintf(stderr," cancr.mod");
fprintf(stderr," canin.mod");
fprintf(stderr," cat_mig.mod");
fprintf(stderr," cat_traub.mod");
fprintf(stderr," catcb.mod");
fprintf(stderr," ch_CavL.mod");
fprintf(stderr," ch_CavN.mod");
fprintf(stderr," ch_KCaS.mod");
fprintf(stderr," ch_Kdrfastngf.mod");
fprintf(stderr," ch_KvAngf.mod");
fprintf(stderr," ch_KvCaB.mod");
fprintf(stderr," ch_leak.mod");
fprintf(stderr," ch_Navngf.mod");
fprintf(stderr," DetAMPANMDA.mod");
fprintf(stderr," DetGABAAB.mod");
fprintf(stderr," gabab.mod");
fprintf(stderr," h_BS.mod");
fprintf(stderr," h_harnett.mod");
fprintf(stderr," h_kole.mod");
fprintf(stderr," h_migliore.mod");
fprintf(stderr," HCN1.mod");
fprintf(stderr," HH2.mod");
fprintf(stderr," hin.mod");
fprintf(stderr," htc.mod");
fprintf(stderr," IC.mod");
fprintf(stderr," ican_sidi.mod");
fprintf(stderr," iccr.mod");
fprintf(stderr," iconc_Ca.mod");
fprintf(stderr," Ih.mod");
fprintf(stderr," ikscr.mod");
fprintf(stderr," IKsin.mod");
fprintf(stderr," Im.mod");
fprintf(stderr," IT.mod");
fprintf(stderr," IT2.mod");
fprintf(stderr," K_Pst.mod");
fprintf(stderr," K_Tst.mod");
fprintf(stderr," kap_BS.mod");
fprintf(stderr," kapcb.mod");
fprintf(stderr," kapin.mod");
fprintf(stderr," kBK.mod");
fprintf(stderr," kca.mod");
fprintf(stderr," kctin.mod");
fprintf(stderr," kdmc_BS.mod");
fprintf(stderr," kdr_BS.mod");
fprintf(stderr," kdrcr.mod");
fprintf(stderr," kdrin.mod");
fprintf(stderr," KdShu2007.mod");
fprintf(stderr," kl.mod");
fprintf(stderr," km.mod");
fprintf(stderr," kv.mod");
fprintf(stderr," my_exp2syn.mod");
fprintf(stderr," MyExp2SynBB.mod");
fprintf(stderr," MyExp2SynNMDABB.mod");
fprintf(stderr," nafcr.mod");
fprintf(stderr," nafx.mod");
fprintf(stderr," Nap_Et2.mod");
fprintf(stderr," nap_sidi.mod");
fprintf(stderr," NaTa_t.mod");
fprintf(stderr," NaTs2_t.mod");
fprintf(stderr," nax_BS.mod");
fprintf(stderr," naz.mod");
fprintf(stderr," Nca.mod");
fprintf(stderr," ProbAMPANMDA_EMS.mod");
fprintf(stderr," ProbGABAAB_EMS.mod");
fprintf(stderr," savedist.mod");
fprintf(stderr," SK_E2.mod");
fprintf(stderr," SKv3_1.mod");
fprintf(stderr," StochKv.mod");
fprintf(stderr," StochKv_deterministic.mod");
fprintf(stderr," tia.mod");
fprintf(stderr," vecstim.mod");
fprintf(stderr," xtra.mod");
fprintf(stderr, "\n");
    }
_ar_traub_reg();
_Ca_reg();
_Ca_HVA_reg();
_Ca_LVAst_reg();
_cadad_reg();
_cadyn_reg();
_CaDynamics_E2_reg();
_cagk_reg();
_cal_mh_reg();
_cal_mig_reg();
_can_mig_reg();
_cancr_reg();
_canin_reg();
_cat_mig_reg();
_cat_traub_reg();
_catcb_reg();
_ch_CavL_reg();
_ch_CavN_reg();
_ch_KCaS_reg();
_ch_Kdrfastngf_reg();
_ch_KvAngf_reg();
_ch_KvCaB_reg();
_ch_leak_reg();
_ch_Navngf_reg();
_DetAMPANMDA_reg();
_DetGABAAB_reg();
_gabab_reg();
_h_BS_reg();
_h_harnett_reg();
_h_kole_reg();
_h_migliore_reg();
_HCN1_reg();
_HH2_reg();
_hin_reg();
_htc_reg();
_IC_reg();
_ican_sidi_reg();
_iccr_reg();
_iconc_Ca_reg();
_Ih_reg();
_ikscr_reg();
_IKsin_reg();
_Im_reg();
_IT_reg();
_IT2_reg();
_K_Pst_reg();
_K_Tst_reg();
_kap_BS_reg();
_kapcb_reg();
_kapin_reg();
_kBK_reg();
_kca_reg();
_kctin_reg();
_kdmc_BS_reg();
_kdr_BS_reg();
_kdrcr_reg();
_kdrin_reg();
_KdShu2007_reg();
_kl_reg();
_km_reg();
_kv_reg();
_my_exp2syn_reg();
_MyExp2SynBB_reg();
_MyExp2SynNMDABB_reg();
_nafcr_reg();
_nafx_reg();
_Nap_Et2_reg();
_nap_sidi_reg();
_NaTa_t_reg();
_NaTs2_t_reg();
_nax_BS_reg();
_naz_reg();
_Nca_reg();
_ProbAMPANMDA_EMS_reg();
_ProbGABAAB_EMS_reg();
_savedist_reg();
_SK_E2_reg();
_SKv3_1_reg();
_StochKv_reg();
_StochKv_deterministic_reg();
_tia_reg();
_vecstim_reg();
_xtra_reg();
}
